import os
import json
import asyncio
import requests
from bs4 import BeautifulSoup
from datetime import datetime
import edge_tts

def fetch_live_ai_video_news():
    print("Fetching real-time AI tools and news...")
    results = []
    
    # 1. HackerNews Search
    try:
        hn_url = "https://hn.algolia.com/api/v1/search?query=ai%20video%20tool&tags=story"
        res = requests.get(hn_url, timeout=10)
        if res.status_code == 200:
            data = res.json()
            for item in data.get("hits", [])[:3]:
                results.append({
                    "source": "HackerNews",
                    "title": item.get("title"),
                    "url": item.get("url") or f"https://news.ycombinator.com/item?id={item.get('objectID')}"
                })
    except Exception as e:
        print(f"Error fetching HN: {e}")

    # 2. GitHub Trending Python
    try:
        gh_url = "https://github.com/trending/python?since=daily"
        headers = {"User-Agent": "Mozilla/5.0"}
        res = requests.get(gh_url, headers=headers, timeout=10)
        if res.status_code == 200:
            soup = BeautifulSoup(res.text, "html.parser")
            for repo in soup.select("article.Box-row")[:3]:
                title = repo.select_one("h2 a").text.strip().replace("\n", "").replace(" ", "")
                desc = repo.select_one("p")
                results.append({
                    "source": "GitHub Trending",
                    "title": title,
                    "description": desc.text.strip() if desc else "No description",
                    "url": f"https://github.com/{title}"
                })
    except Exception as e:
        print(f"Error scraping GitHub Trending: {e}")

    return results

def generate_nova_factory_plan(findings):
    top_item = findings[0].get("title", "un nouvel outil IA vidéo") if findings else "les dernières IA vidéo"
    
    clean_voice_text = f"Arrête de payer pour tes montages vidéo. Cet outil IA gratuit vient tout changer. Si tu crées du contenu, tu dois absolument tester {top_item}. Il te permet d'automatiser ta recherche et de trouver les meilleures pépites sans débourser un centime. Abonne-toi pour ne rien rater !"

    plan_md = f"""# 🎬 NOVA AI Video Factory - Production Plan (0 DH)
**Date :** {datetime.now().strftime('%Y-%m-%d')}
**Sujet Principal :** {top_item}

---

### 🎙️ Script Voiceover (Audio Inclus)
> "{clean_voice_text}"

---

### 🎨 Scene Prompt Matrix (Rotation des Crédits Gratuits)

| Scène | Outil Recommandé | Type de Prompt à Saisir | Allocation Crédits |
| :--- | :--- | :--- | :--- |
| **0-3s (Hook)** | **Dreamina** | `Cinematic close-up of a surreal glowing AI robot looking at a phone, ultra realistic, 4k` | ~10-20 daily credits |
| **3-15s (Core 1)** | **Kling AI** | `A person shocked working at a desk, laptop screen showing futuristic AI code, realistic physical movement` | ~10 daily credits |
| **15-30s (Core 2)** | **Hailuo AI** | `Hyper-realistic slow motion scene of digital technology dissolving into gold particles, photorealistic physics` | Free daily allowance |
| **30-45s (CTA)** | **Pika** | `Animated 3D subscribe button bouncing with viral comic explosion effect, 9:16 vertical` | Free monthly credits |

---

### ✂️ CapCut Assembly Checklist
1. Import `audio/latest_voiceover.mp3` generated by GitHub Actions.
2. Generate videos using the prompts above on Dreamina / Kling / Hailuo / Pika.
3. Import the generated clips and line them up with the voiceover.
4. Click **Text > Auto Captions** in CapCut.
5. Export in 1080x1920 (9:16) & publish.
"""
    return plan_md, clean_voice_text

async def generate_audio_voiceover(text, output_path):
    print("Generating voiceover MP3...")
    communicate = edge_tts.Communicate(text, "fr-FR-HenriNeural")
    await communicate.save(output_path)

def run_research():
    print("=== NOVA Autonomous AI Video Agent ===")
    live_findings = fetch_live_ai_video_news()
    
    # 1. Save Research JSON
    report_data = {
        "timestamp": datetime.now().isoformat(),
        "status": "completed",
        "stack_budget": "0 DH",
        "findings": live_findings
    }
    os.makedirs("reports", exist_ok=True)
    with open("reports/research_latest.json", "w", encoding="utf-8") as f:
        json.dump(report_data, f, ensure_ascii=False, indent=2)
        
    # 2. Save Production Plan & Prompts
    plan_content, clean_voice_text = generate_nova_factory_plan(live_findings)
    os.makedirs("scripts", exist_ok=True)
    with open("scripts/latest_video_script.md", "w", encoding="utf-8") as f:
        f.write(plan_content)
        
    # 3. Generate Audio Voiceover MP3
    os.makedirs("audio", exist_ok=True)
    audio_path = "audio/latest_voiceover.mp3"
    asyncio.run(generate_audio_voiceover(clean_voice_text, audio_path))
        
    print("✓ Full 0-DH Pipeline executed successfully!")

if __name__ == "__main__":
    run_research()
